/*
** AUTOGENERATED CODE, DO NOT EDIT
**
** Author(s):
**  - Cedric GESTES <gestes@aldebaran-robotics.com>
**
** Copyright (C) 2010 Aldebaran Robotics
*/

#ifndef I_WANT_HXX
#error("do not include hxx in your code")
#endif

#ifndef  QI_FUNCTORS_MEMBERFUNCTOR_HXX_
#define QI_FUNCTORS_MEMBERFUNCTOR_HXX_

#include <qi/functors/functor.hpp>

namespace qi {
namespace detail {

  template < typename C, typename R>
  class MemberFunctor_0 : public Functor
  {
  public:
    typedef R(C::*FunctionType) ();

    MemberFunctor_0(C *pObject, FunctionType pFunction)
      : fObject(pObject),
        fFunction(pFunction)
    {}

    R operator()() {
      return (R)(fObject->*fFunction)();
    }

    void call(qi::serialization::SerializedData &params, qi::serialization::SerializedData& result) const {
      QI_FUNCTOR_ASSUME_NBR_PARAMS(params, 0);

      result.write((fObject->*fFunction)());
    };

  private:
    C            *fObject;
    FunctionType  fFunction;
  };

  template <typename P0,  typename C, typename R>
  class MemberFunctor_1 : public Functor
  {
  public:
    typedef R(C::*FunctionType) (const P0 &p0);

    MemberFunctor_1(C *pObject, FunctionType pFunction)
      : fObject(pObject),
        fFunction(pFunction)
    {}

    R operator()(const P0 &p0) {
      return (R)(fObject->*fFunction)(p0);
    }

    void call(qi::serialization::SerializedData &params, qi::serialization::SerializedData& result) const {
      QI_FUNCTOR_ASSUME_NBR_PARAMS(params, 1);
      P0 p0;

      params.read<P0>(p0);
      result.write((fObject->*fFunction)(p0));
    };

  private:
    C            *fObject;
    FunctionType  fFunction;
  };

  template <typename P0, typename P1,  typename C, typename R>
  class MemberFunctor_2 : public Functor
  {
  public:
    typedef R(C::*FunctionType) (const P0 &p0, const P1 &p1);

    MemberFunctor_2(C *pObject, FunctionType pFunction)
      : fObject(pObject),
        fFunction(pFunction)
    {}

    R operator()(const P0 &p0, const P1 &p1) {
      return (R)(fObject->*fFunction)(p0, p1);
    }

    void call(qi::serialization::SerializedData &params, qi::serialization::SerializedData& result) const {
      QI_FUNCTOR_ASSUME_NBR_PARAMS(params, 2);
      P0 p0;
      P1 p1;

      params.read<P0>(p0);
      params.read<P1>(p1);
      result.write((fObject->*fFunction)(p0, p1));
    };

  private:
    C            *fObject;
    FunctionType  fFunction;
  };

  template <typename P0, typename P1, typename P2,  typename C, typename R>
  class MemberFunctor_3 : public Functor
  {
  public:
    typedef R(C::*FunctionType) (const P0 &p0, const P1 &p1, const P2 &p2);

    MemberFunctor_3(C *pObject, FunctionType pFunction)
      : fObject(pObject),
        fFunction(pFunction)
    {}

    R operator()(const P0 &p0, const P1 &p1, const P2 &p2) {
      return (R)(fObject->*fFunction)(p0, p1, p2);
    }

    void call(qi::serialization::SerializedData &params, qi::serialization::SerializedData& result) const {
      QI_FUNCTOR_ASSUME_NBR_PARAMS(params, 3);
      P0 p0;
      P1 p1;
      P2 p2;

      params.read<P0>(p0);
      params.read<P1>(p1);
      params.read<P2>(p2);
      result.write((fObject->*fFunction)(p0, p1, p2));
    };

  private:
    C            *fObject;
    FunctionType  fFunction;
  };

  template <typename P0, typename P1, typename P2, typename P3,  typename C, typename R>
  class MemberFunctor_4 : public Functor
  {
  public:
    typedef R(C::*FunctionType) (const P0 &p0, const P1 &p1, const P2 &p2, const P3 &p3);

    MemberFunctor_4(C *pObject, FunctionType pFunction)
      : fObject(pObject),
        fFunction(pFunction)
    {}

    R operator()(const P0 &p0, const P1 &p1, const P2 &p2, const P3 &p3) {
      return (R)(fObject->*fFunction)(p0, p1, p2, p3);
    }

    void call(qi::serialization::SerializedData &params, qi::serialization::SerializedData& result) const {
      QI_FUNCTOR_ASSUME_NBR_PARAMS(params, 4);
      P0 p0;
      P1 p1;
      P2 p2;
      P3 p3;

      params.read<P0>(p0);
      params.read<P1>(p1);
      params.read<P2>(p2);
      params.read<P3>(p3);
      result.write((fObject->*fFunction)(p0, p1, p2, p3));
    };

  private:
    C            *fObject;
    FunctionType  fFunction;
  };

  template <typename P0, typename P1, typename P2, typename P3, typename P4,  typename C, typename R>
  class MemberFunctor_5 : public Functor
  {
  public:
    typedef R(C::*FunctionType) (const P0 &p0, const P1 &p1, const P2 &p2, const P3 &p3, const P4 &p4);

    MemberFunctor_5(C *pObject, FunctionType pFunction)
      : fObject(pObject),
        fFunction(pFunction)
    {}

    R operator()(const P0 &p0, const P1 &p1, const P2 &p2, const P3 &p3, const P4 &p4) {
      return (R)(fObject->*fFunction)(p0, p1, p2, p3, p4);
    }

    void call(qi::serialization::SerializedData &params, qi::serialization::SerializedData& result) const {
      QI_FUNCTOR_ASSUME_NBR_PARAMS(params, 5);
      P0 p0;
      P1 p1;
      P2 p2;
      P3 p3;
      P4 p4;

      params.read<P0>(p0);
      params.read<P1>(p1);
      params.read<P2>(p2);
      params.read<P3>(p3);
      params.read<P4>(p4);
      result.write((fObject->*fFunction)(p0, p1, p2, p3, p4));
    };

  private:
    C            *fObject;
    FunctionType  fFunction;
  };

  template <typename P0, typename P1, typename P2, typename P3, typename P4, typename P5,  typename C, typename R>
  class MemberFunctor_6 : public Functor
  {
  public:
    typedef R(C::*FunctionType) (const P0 &p0, const P1 &p1, const P2 &p2, const P3 &p3, const P4 &p4, const P5 &p5);

    MemberFunctor_6(C *pObject, FunctionType pFunction)
      : fObject(pObject),
        fFunction(pFunction)
    {}

    R operator()(const P0 &p0, const P1 &p1, const P2 &p2, const P3 &p3, const P4 &p4, const P5 &p5) {
      return (R)(fObject->*fFunction)(p0, p1, p2, p3, p4, p5);
    }

    void call(qi::serialization::SerializedData &params, qi::serialization::SerializedData& result) const {
      QI_FUNCTOR_ASSUME_NBR_PARAMS(params, 6);
      P0 p0;
      P1 p1;
      P2 p2;
      P3 p3;
      P4 p4;
      P5 p5;

      params.read<P0>(p0);
      params.read<P1>(p1);
      params.read<P2>(p2);
      params.read<P3>(p3);
      params.read<P4>(p4);
      params.read<P5>(p5);
      result.write((fObject->*fFunction)(p0, p1, p2, p3, p4, p5));
    };

  private:
    C            *fObject;
    FunctionType  fFunction;
  };

}
}
#endif  // QI_FUNCTORS_MEMBERFUNCTOR_HXX_
