/*
* AUTOGENERATED CODE, DO NOT EDIT
*
*  Author(s):
*  - Cedric GESTES <gestes@aldebaran-robotics.com>
*
*  Copyright (C) 2010, 2012 Aldebaran Robotics
*/


#pragma once
#ifndef _QIMESSAGING_DETAILS_VOIDMEMBERFUNCTOR_HXX_
#define _QIMESSAGING_DETAILS_VOIDMEMBERFUNCTOR_HXX_

# include <qimessaging/functor.hpp>

namespace qi {
namespace detail {


  template < typename C>
  class MemberFunctor_0< C, void> : public Functor
  {
  public:
    typedef void(C::*FunctionType) ();

    MemberFunctor_0(C *pObject, FunctionType pFunction)
      : fObject(pObject),
        fFunction(pFunction) {
    }

    void operator()() {
      (fObject->*fFunction)();
    }

    void call(const qi::FunctorParameters &params, qi::FunctorResult result) const {
      QI_FUNCTOR_ASSUME_NBR_PARAMS(params, 0);
      qi::DataStream dsi(params.buffer());
      qi::Buffer buf;



      if (sanityCheckAndReport(dsi, result)) {
        (fObject->*fFunction)();
        result.setValue(buf);
      }
    };

  private:
    C            *fObject;
    FunctionType  fFunction;
  };


  template <typename P0,  typename C>
  class MemberFunctor_1<P0,  C, void> : public Functor
  {
  public:
    typedef void(C::*FunctionType) (const P0 &p0);

    MemberFunctor_1(C *pObject, FunctionType pFunction)
      : fObject(pObject),
        fFunction(pFunction) {
    }

    void operator()(const P0 &p0) {
      (fObject->*fFunction)(p0);
    }

    void call(const qi::FunctorParameters &params, qi::FunctorResult result) const {
      QI_FUNCTOR_ASSUME_NBR_PARAMS(params, 1);
      qi::DataStream dsi(params.buffer());
      qi::Buffer buf;

      P0 p0;


      dsi >> p0;
      if (sanityCheckAndReport(dsi, result)) {
        (fObject->*fFunction)(p0);
        result.setValue(buf);
      }
    };

  private:
    C            *fObject;
    FunctionType  fFunction;
  };


  template <typename P0, typename P1,  typename C>
  class MemberFunctor_2<P0, P1,  C, void> : public Functor
  {
  public:
    typedef void(C::*FunctionType) (const P0 &p0, const P1 &p1);

    MemberFunctor_2(C *pObject, FunctionType pFunction)
      : fObject(pObject),
        fFunction(pFunction) {
    }

    void operator()(const P0 &p0, const P1 &p1) {
      (fObject->*fFunction)(p0, p1);
    }

    void call(const qi::FunctorParameters &params, qi::FunctorResult result) const {
      QI_FUNCTOR_ASSUME_NBR_PARAMS(params, 2);
      qi::DataStream dsi(params.buffer());
      qi::Buffer buf;

      P0 p0;
      P1 p1;


      dsi >> p0;
      dsi >> p1;
      if (sanityCheckAndReport(dsi, result)) {
        (fObject->*fFunction)(p0, p1);
        result.setValue(buf);
      }
    };

  private:
    C            *fObject;
    FunctionType  fFunction;
  };


  template <typename P0, typename P1, typename P2,  typename C>
  class MemberFunctor_3<P0, P1, P2,  C, void> : public Functor
  {
  public:
    typedef void(C::*FunctionType) (const P0 &p0, const P1 &p1, const P2 &p2);

    MemberFunctor_3(C *pObject, FunctionType pFunction)
      : fObject(pObject),
        fFunction(pFunction) {
    }

    void operator()(const P0 &p0, const P1 &p1, const P2 &p2) {
      (fObject->*fFunction)(p0, p1, p2);
    }

    void call(const qi::FunctorParameters &params, qi::FunctorResult result) const {
      QI_FUNCTOR_ASSUME_NBR_PARAMS(params, 3);
      qi::DataStream dsi(params.buffer());
      qi::Buffer buf;

      P0 p0;
      P1 p1;
      P2 p2;


      dsi >> p0;
      dsi >> p1;
      dsi >> p2;
      if (sanityCheckAndReport(dsi, result)) {
        (fObject->*fFunction)(p0, p1, p2);
        result.setValue(buf);
      }
    };

  private:
    C            *fObject;
    FunctionType  fFunction;
  };


  template <typename P0, typename P1, typename P2, typename P3,  typename C>
  class MemberFunctor_4<P0, P1, P2, P3,  C, void> : public Functor
  {
  public:
    typedef void(C::*FunctionType) (const P0 &p0, const P1 &p1, const P2 &p2, const P3 &p3);

    MemberFunctor_4(C *pObject, FunctionType pFunction)
      : fObject(pObject),
        fFunction(pFunction) {
    }

    void operator()(const P0 &p0, const P1 &p1, const P2 &p2, const P3 &p3) {
      (fObject->*fFunction)(p0, p1, p2, p3);
    }

    void call(const qi::FunctorParameters &params, qi::FunctorResult result) const {
      QI_FUNCTOR_ASSUME_NBR_PARAMS(params, 4);
      qi::DataStream dsi(params.buffer());
      qi::Buffer buf;

      P0 p0;
      P1 p1;
      P2 p2;
      P3 p3;


      dsi >> p0;
      dsi >> p1;
      dsi >> p2;
      dsi >> p3;
      if (sanityCheckAndReport(dsi, result)) {
        (fObject->*fFunction)(p0, p1, p2, p3);
        result.setValue(buf);
      }
    };

  private:
    C            *fObject;
    FunctionType  fFunction;
  };


  template <typename P0, typename P1, typename P2, typename P3, typename P4,  typename C>
  class MemberFunctor_5<P0, P1, P2, P3, P4,  C, void> : public Functor
  {
  public:
    typedef void(C::*FunctionType) (const P0 &p0, const P1 &p1, const P2 &p2, const P3 &p3, const P4 &p4);

    MemberFunctor_5(C *pObject, FunctionType pFunction)
      : fObject(pObject),
        fFunction(pFunction) {
    }

    void operator()(const P0 &p0, const P1 &p1, const P2 &p2, const P3 &p3, const P4 &p4) {
      (fObject->*fFunction)(p0, p1, p2, p3, p4);
    }

    void call(const qi::FunctorParameters &params, qi::FunctorResult result) const {
      QI_FUNCTOR_ASSUME_NBR_PARAMS(params, 5);
      qi::DataStream dsi(params.buffer());
      qi::Buffer buf;

      P0 p0;
      P1 p1;
      P2 p2;
      P3 p3;
      P4 p4;


      dsi >> p0;
      dsi >> p1;
      dsi >> p2;
      dsi >> p3;
      dsi >> p4;
      if (sanityCheckAndReport(dsi, result)) {
        (fObject->*fFunction)(p0, p1, p2, p3, p4);
        result.setValue(buf);
      }
    };

  private:
    C            *fObject;
    FunctionType  fFunction;
  };


  template <typename P0, typename P1, typename P2, typename P3, typename P4, typename P5,  typename C>
  class MemberFunctor_6<P0, P1, P2, P3, P4, P5,  C, void> : public Functor
  {
  public:
    typedef void(C::*FunctionType) (const P0 &p0, const P1 &p1, const P2 &p2, const P3 &p3, const P4 &p4, const P5 &p5);

    MemberFunctor_6(C *pObject, FunctionType pFunction)
      : fObject(pObject),
        fFunction(pFunction) {
    }

    void operator()(const P0 &p0, const P1 &p1, const P2 &p2, const P3 &p3, const P4 &p4, const P5 &p5) {
      (fObject->*fFunction)(p0, p1, p2, p3, p4, p5);
    }

    void call(const qi::FunctorParameters &params, qi::FunctorResult result) const {
      QI_FUNCTOR_ASSUME_NBR_PARAMS(params, 6);
      qi::DataStream dsi(params.buffer());
      qi::Buffer buf;

      P0 p0;
      P1 p1;
      P2 p2;
      P3 p3;
      P4 p4;
      P5 p5;


      dsi >> p0;
      dsi >> p1;
      dsi >> p2;
      dsi >> p3;
      dsi >> p4;
      dsi >> p5;
      if (sanityCheckAndReport(dsi, result)) {
        (fObject->*fFunction)(p0, p1, p2, p3, p4, p5);
        result.setValue(buf);
      }
    };

  private:
    C            *fObject;
    FunctionType  fFunction;
  };


  template <typename P0, typename P1, typename P2, typename P3, typename P4, typename P5, typename P6,  typename C>
  class MemberFunctor_7<P0, P1, P2, P3, P4, P5, P6,  C, void> : public Functor
  {
  public:
    typedef void(C::*FunctionType) (const P0 &p0, const P1 &p1, const P2 &p2, const P3 &p3, const P4 &p4, const P5 &p5, const P6 &p6);

    MemberFunctor_7(C *pObject, FunctionType pFunction)
      : fObject(pObject),
        fFunction(pFunction) {
    }

    void operator()(const P0 &p0, const P1 &p1, const P2 &p2, const P3 &p3, const P4 &p4, const P5 &p5, const P6 &p6) {
      (fObject->*fFunction)(p0, p1, p2, p3, p4, p5, p6);
    }

    void call(const qi::FunctorParameters &params, qi::FunctorResult result) const {
      QI_FUNCTOR_ASSUME_NBR_PARAMS(params, 7);
      qi::DataStream dsi(params.buffer());
      qi::Buffer buf;

      P0 p0;
      P1 p1;
      P2 p2;
      P3 p3;
      P4 p4;
      P5 p5;
      P6 p6;


      dsi >> p0;
      dsi >> p1;
      dsi >> p2;
      dsi >> p3;
      dsi >> p4;
      dsi >> p5;
      dsi >> p6;
      if (sanityCheckAndReport(dsi, result)) {
        (fObject->*fFunction)(p0, p1, p2, p3, p4, p5, p6);
        result.setValue(buf);
      }
    };

  private:
    C            *fObject;
    FunctionType  fFunction;
  };


  template <typename P0, typename P1, typename P2, typename P3, typename P4, typename P5, typename P6, typename P7,  typename C>
  class MemberFunctor_8<P0, P1, P2, P3, P4, P5, P6, P7,  C, void> : public Functor
  {
  public:
    typedef void(C::*FunctionType) (const P0 &p0, const P1 &p1, const P2 &p2, const P3 &p3, const P4 &p4, const P5 &p5, const P6 &p6, const P7 &p7);

    MemberFunctor_8(C *pObject, FunctionType pFunction)
      : fObject(pObject),
        fFunction(pFunction) {
    }

    void operator()(const P0 &p0, const P1 &p1, const P2 &p2, const P3 &p3, const P4 &p4, const P5 &p5, const P6 &p6, const P7 &p7) {
      (fObject->*fFunction)(p0, p1, p2, p3, p4, p5, p6, p7);
    }

    void call(const qi::FunctorParameters &params, qi::FunctorResult result) const {
      QI_FUNCTOR_ASSUME_NBR_PARAMS(params, 8);
      qi::DataStream dsi(params.buffer());
      qi::Buffer buf;

      P0 p0;
      P1 p1;
      P2 p2;
      P3 p3;
      P4 p4;
      P5 p5;
      P6 p6;
      P7 p7;


      dsi >> p0;
      dsi >> p1;
      dsi >> p2;
      dsi >> p3;
      dsi >> p4;
      dsi >> p5;
      dsi >> p6;
      dsi >> p7;
      if (sanityCheckAndReport(dsi, result)) {
        (fObject->*fFunction)(p0, p1, p2, p3, p4, p5, p6, p7);
        result.setValue(buf);
      }
    };

  private:
    C            *fObject;
    FunctionType  fFunction;
  };


  template <typename P0, typename P1, typename P2, typename P3, typename P4, typename P5, typename P6, typename P7, typename P8,  typename C>
  class MemberFunctor_9<P0, P1, P2, P3, P4, P5, P6, P7, P8,  C, void> : public Functor
  {
  public:
    typedef void(C::*FunctionType) (const P0 &p0, const P1 &p1, const P2 &p2, const P3 &p3, const P4 &p4, const P5 &p5, const P6 &p6, const P7 &p7, const P8 &p8);

    MemberFunctor_9(C *pObject, FunctionType pFunction)
      : fObject(pObject),
        fFunction(pFunction) {
    }

    void operator()(const P0 &p0, const P1 &p1, const P2 &p2, const P3 &p3, const P4 &p4, const P5 &p5, const P6 &p6, const P7 &p7, const P8 &p8) {
      (fObject->*fFunction)(p0, p1, p2, p3, p4, p5, p6, p7, p8);
    }

    void call(const qi::FunctorParameters &params, qi::FunctorResult result) const {
      QI_FUNCTOR_ASSUME_NBR_PARAMS(params, 9);
      qi::DataStream dsi(params.buffer());
      qi::Buffer buf;

      P0 p0;
      P1 p1;
      P2 p2;
      P3 p3;
      P4 p4;
      P5 p5;
      P6 p6;
      P7 p7;
      P8 p8;


      dsi >> p0;
      dsi >> p1;
      dsi >> p2;
      dsi >> p3;
      dsi >> p4;
      dsi >> p5;
      dsi >> p6;
      dsi >> p7;
      dsi >> p8;
      if (sanityCheckAndReport(dsi, result)) {
        (fObject->*fFunction)(p0, p1, p2, p3, p4, p5, p6, p7, p8);
        result.setValue(buf);
      }
    };

  private:
    C            *fObject;
    FunctionType  fFunction;
  };

}
}
#endif  // _QIMESSAGING_DETAILS_VOIDMEMBERFUNCTOR_HXX_
