<IDL>
<class name="Task">
  <method name="getName">
    <return type="string" />
  </method>
  <method name="setParam">
    <return type="string" />
    <argument type="string" />
  </method>
  <method name="step">
    <return type="string" />
    <argument type="uint" />
  </method>
  <method name="getLastResult">
    <return type="string" />
  </method>
  <signal name="onParamChanged"><argument type="string" /></signal>
  <signal name="onStep"><argument type="string" /></signal>
</class>
<class name="TaskGenerator">
  <method name="newTask">
    <return type="TaskProxyPtr" />
    <argument type="string" />
  </method>
  <method name="step">
    <return type="void" />
    <argument type="uint" />
  </method>
  <method name="taskCount">
    <return type="uint64" />
  </method>
  <method name="tasks">
    <return type="[TaskProxyPtr]" />
  </method>
</class>
</IDL>