#pragma once
/*
 * Copyright (c) 2012 Aldebaran Robotics. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the COPYING file.
 */


#ifndef _QI_PATH_CONF_HPP_
#define _QI_PATH_CONF_HPP_

#include <string>
#include <vector>
#include <qi/api.hpp>

namespace qi {
  namespace path {

      /**
       * Recursively parse <sdk/share/qi/path.conf> files
       * Generated by qibuild, this makes it possible to find
       * files from the depencies build dir or sources
       */
      QI_API std::vector<std::string> parseQiPathConf(const std::string &prefix);

  } // path
} // qi

#endif
