<IDL>
<class name="qi::Adder">
  <method name="addTwo">
    <return type="i" />
    <argument type="i" />
    <argument type="i" />
  </method>
  <property name="value" type="i" />
  <signal  name="onAdd" >
    <argument type="i" />
  </signal>
</class>
</IDL>
