#!/usr/bin/env python

"""
Little tool to manage all maven operations for qiMessaging Java bindings

"""

from optparse import OptionParser
import subprocess


"""
Global values
"""
__usage__  = "./do --platform={android, desktop}"
jarname    = "nativeqimessaging-"#platform
default_repo_url = "/tmp/maven/"#jarname

def jar_package(jarname, file_list, config=None):
    """
    Package file info jar file
    """
    callee = ["qimvn", "jar"]
    if config:
        callee += ["-c", config]

    callee += [jarname] + file_list
    return subprocess.call(callee)

def deploy(artifact_id, filename, url, version = "1.0-SNAPSHOT", group_id = "com.aldebaran"):
    """
    Call to maven deploy goal
    """
    skip_test   = "-Dmaven.test.skip=true"
    group_id    = ["--groupId", group_id]
    version     = ["--version", version]
    artifact_id = ["--artifactId", artifact_id]
    url         = ["--url", url]

    callee = ["qimvn", "deploy", filename] + group_id + version + artifact_id + url
    return subprocess.call(callee)

def deploy_native_package(platform):
    """
    Package qiMessaging Java bindings and
    deploy them with Maven
    """
    pom_name = "pom-" + platform + ".xml"
    callee = ["qimvn", "package", "--pom", pom_name, "--skip-test"]

    if subprocess.call(callee) is not 0:
        return 1


    jarname = "qimessaging"
    if platform == "android":
        jarname += "-apklib"
    jarname += "-1.0-SNAPSHOT"
    if platform == "android":
        jarname += ".apklib"
    else:
        jarname += ".jar"

    url = "file:///tmp/maven/qimessaging-" + platform
    return deploy("qimessaging", "target/" + jarname, url)

def package_native_libraries(platform):
    """
    Package all native libraries in a jar and
    deploy them with Maven
    """

    native_librairies = ["qi", "qitype", "qimessaging", "qimessagingjni"]
    artifact_id = jarname + platform
    jar_name = artifact_id + ".jar"
    url = "file://" + default_repo_url + artifact_id
    config = None

    if platform == "android":
        native_librairies += ["gnustl_shared"]
        config = "android"

    # Generate a jar package containing native libraries
    if jar_package(jar_name, native_librairies, config) is not 0:
        return 1

    # Deploy generated jar
    if deploy(artifact_id, jar_name, url) is not 0:
        return 1
    # callee = ["qimvn", "deploy", jar_name, "--artifactId", artifact_id]
    # callee += ["--groupId", "com.aldebaran", "--url", url]
    # if subprocess.call(callee) is not 0:
    #     return 1

    # Remove generated jar
    callee = ["rm", jar_name]
    return subprocess.call(callee)

def deploy_bindings(platform):
    """
    Deploy qimessaging bindings using Maven
    """
    if package_native_libraries(platform) is not 0:
        return False
    if deploy_native_package(platform) is not 0:
        return False
    return True

if __name__ == "__main__":
    opt_parser = OptionParser(usage=__usage__)

    opt_parser.set_defaults(
        platform = "desktop",
        dest = default_repo_url
        )

    opt_parser.add_option("--platform=", dest="platform", help="Platform to configure")
    (opts, _args) = opt_parser.parse_args()

    deploy_bindings(opts.platform)
