#!/usr/bin/env python
##
## Author(s):
##  - Cedric GESTES <gestes@aldebaran-robotics.com>
##
## Copyright (C) 2010 Aldebaran Robotics
##

import os
from Cheetah.Template import Template

def generate_list(tpl, count, sep = ", ", begin = False, end = False):
    result = ""
    if begin and count:
        result += sep
    for i in range(count):
        result += tpl % { 'count' : i }
        if i != count - 1 or end:
            result += sep
    return result

def generate_callparam_list(count):
    t = "p%(count)d"
    return generate_list(t, count)

def generate_typename_list(count, begin = False, end = False):
    t = "typename P%(count)d"
    return generate_list(t, count, begin=begin, end=end)

def generate_type_list(count, begin = False, end = False):
    t = "P%(count)d"
    return generate_list(t, count, begin=begin, end=end)

def generate_param_list(count, begin = False, end = False):
    t = "const P%(count)d &p%(count)d"
    return generate_list(t, count, begin=begin, end=end)

def generate_arg_list(count, begin = False, end = False):
    t = "p%(count)d"
    return generate_list(t, count, begin=begin, end=end)

def generate_argpush_list(count):
    t = "args.push_back(p%(count)d);"
    return generate_list(t, count, sep=" ")


def generate_file(src, dst, count):
    code = Template(file = src, searchList = [ { 'count': range(count),
                                                 'autogen' : "AUTOGENERATED CODE, DO NOT EDIT" }])
    with open(dst, "w") as f:
        f.write(str(code))

if __name__ == "__main__":
    os.chdir(os.path.dirname(__file__))
    print "cd", os.path.dirname(__file__)
    generate_file("../qi/functors/memberfunctor.hxx.in"    , "../qi/functors/memberfunctor.hxx"    , 7)
    generate_file("../qi/functors/voidmemberfunctor.hxx.in", "../qi/functors/voidmemberfunctor.hxx", 7)
    generate_file("../qi/functors/functor.hxx.in"          , "../qi/functors/functor.hxx"          , 7)
    generate_file("../qi/functors/voidfunctor.hxx.in"      , "../qi/functors/voidfunctor.hxx"      , 7)
    generate_file("../qi/functors/makefunctor.hpp.in"      , "../qi/functors/makefunctor.hpp"      , 7)
    generate_file("../qi/functors/callfunctor.hpp.in"      , "../qi/functors/callfunctor.hpp"      , 7)
    generate_file("../qi/nodes/client_node.hpp.in"         , "../qi/nodes/client_node.hpp"         , 7)
    generate_file("../qi/nodes/client_node.hxx.in"         , "../qi/nodes/client_node.hxx"         , 7)
